# Generated by Django 6.1.1 on 2026-09-10 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('webcam', 'Webcam')], default='image', max_length=10)),
                ('source_file_name', models.CharField(blank=True, max_length=255)),
                ('cloud_url', models.URLField(blank=True, null=True)),
                ('room_name', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('behaviour', models.CharField(choices=[('looking_around', 'Looking around'), ('no_cheating', 'Normal'), ('phone_use', 'Cheating')], max_length=30)),
                ('confidence', models.FloatField(default=0.0)),
                ('bbox_xmin', models.IntegerField()),
                ('bbox_ymin', models.IntegerField()),
                ('bbox_xmax', models.IntegerField()),
                ('bbox_ymax', models.IntegerField()),
                ('seat_label', models.CharField(blank=True, max_length=20, null=True)),
                ('detected_time', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='detection.session')),
            ],
        ),
    ]
