# Generated by Django 6.1.1 on 2026-09-14 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='snapshot',
            field=models.ImageField(blank=True, null=True, upload_to='detections/'),
        ),
    ]
