# Generated by Django 6.1.1 on 2026-09-14 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_detection_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='behaviour',
            field=models.CharField(choices=[('looking_around', 'Looking around'), ('no_cheating', 'No cheating'), ('phone_use', 'Phone use')], max_length=30),
        ),
    ]
